### ISSUE TITLE
Impossible to build in Android for react-native repository

### ISSUE THREAD

**Issue by madjique** [Survicate/survicate-react-native-sdk#74]
Following the react native [documentation](https://developers.survicate.com/mobile-sdk/react-native/)

building on android, couldn't find the repository 

![Capture d’écran 2024-01-29 à 11 08 33](https://github.com/Survicate/survicate-react-native-sdk/assets/34186054/c6a25352-d7c1-4927-ab97-fec7240d7db4)

**Comment by SurvicatePawelGodlewski** [comment]
@madjique Hi. Could you please double check if you have added maven url into allProjects repositories?

**Comment by madjique** [comment]
> @madjique Hi. Could you please double check if you have added maven url into allProjects repositories?

yes all steps listed in the documentation have been done

**Comment by SurvicatePawelGodlewski** [comment]
@madjique I am having issues with reproducing this issue? Could you provide code snippets for reproduction?

**Comment by madjique** [comment]
here it is
android/app/src/main/AndroidManifest.xml
```XML
<application ... >
...
  <meta-data 
            android:name="com.survicate.surveys.workspaceKey" 
            android:value="***PasteYourKey***"/>
...
</application>
```

android/build.gradle
```Javascript
repositories {
    google()
    maven { url 'https://repo.survicate.com' }
    mavenCentral()
}
```

package.json
```JSON
    "@survicate/react-native-survicate": "4.0.1",
```

**Comment by SurvicatePawelGodlewski** [comment]
@madjique Is the repositories inside allProjects block or buildscript block?

**Comment by madjique** [comment]
> @madjique Is the repositories inside allProjects block or buildscript block?

@SurvicatePawelGodlewski  `buildscript`

**Comment by SurvicatePawelGodlewski** [comment]
@madjique Please move it to allProjects and it should work like a charm

**Comment by madjique** [comment]
> @madjique Please move it to allProjects and it should work like a charm

It did work thanks for help @SurvicatePawelGodlewski
